package com.company.loan.service;
import com.company.loan.model.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger; import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service;
import java.net.URI; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.Base64;

/** JSON REST client for IBM ODM DecOps. */
@Service public class OdmRestDecisionService {
 private static final Logger log=LoggerFactory.getLogger(OdmRestDecisionService.class); private final ObjectMapper mapper; private final HttpClient client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build(); private final URI endpoint; private final String username,password,decisionId;
 public OdmRestDecisionService(ObjectMapper mapper,@Value("${odm.rest.endpoint:http://localhost:9060/DecisionService/rest/v1/DecConfig/1.0/DecOps/1.0}")String endpoint,@Value("${odm.rest.username:odmAdmin}")String username,@Value("${odm.rest.password:odmAdmin}")String password,@Value("${odm.rest.decision-id:string1}")String decisionId){this.mapper=mapper;this.endpoint=URI.create(endpoint);this.username=username;this.password=password;this.decisionId=decisionId;}
 public OdmRestDecisionResponse execute(LoanApplication application){try{String payload=mapper.writerWithDefaultPrettyPrinter().writeValueAsString(request(application));log.info("Calling IBM ODM REST service at {} (DecisionID={})",endpoint,decisionId);HttpRequest.Builder r=HttpRequest.newBuilder(endpoint).timeout(Duration.ofSeconds(30)).header("Content-Type","application/json").header("Accept","application/json").POST(HttpRequest.BodyPublishers.ofString(payload,StandardCharsets.UTF_8));if(!username.isBlank()){String t=Base64.getEncoder().encodeToString((username+":"+password).getBytes(StandardCharsets.UTF_8));r.header("Authorization","Basic "+t);}HttpResponse<String> response=client.send(r.build(),HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));log.info("IBM ODM REST service returned HTTP {}",response.statusCode());return new OdmRestDecisionResponse(response.statusCode(),payload,pretty(response.body()));}catch(Exception e){throw new IllegalStateException("IBM ODM REST invocation failed: "+e.getMessage(),e);}}
 private ObjectNode request(LoanApplication app){ObjectNode n=mapper.createObjectNode();n.set("loan",loanApplication(app));n.put("DecisionID",decisionId);return n;}
 private ObjectNode loanApplication(LoanApplication a){ObjectNode n=mapper.createObjectNode();n.set("applicant",applicant(a==null?null:a.getApplicant()));n.set("loan",loan(a==null?null:a.getLoan()));ObjectNode v=n.putObject("validationResult");v.put("eligible",false);v.put("decision","");v.putArray("messages");return n;}
 private ObjectNode applicant(Applicant a){ObjectNode n=o();if(a==null)return n;text(n,"applicantId",a.getApplicantId());text(n,"firstName",a.getFirstName());text(n,"lastName",a.getLastName());num(n,"age",a.getAge());text(n,"gender",a.getGender());n.set("details",details(a.getDetails()));n.set("employment",employment(a.getEmployment()));n.set("address",address(a.getAddress()));n.set("creditHistory",credit(a.getCreditHistory()));n.set("income",income(a.getIncome()));n.set("bankAccount",bank(a.getBankDetails()));return n;}
 private ObjectNode details(ApplicantDetails d){ObjectNode n=o();if(d==null)return n;text(n,"panNumber",d.getPan());text(n,"aadhaarNumber",d.getAadhaar());text(n,"maritalStatus",d.getMaritalStatus());num(n,"dependents",d.getDependents());bool(n,"existingCustomer",d.getExistingCustomer());return n;}
 private ObjectNode employment(Employment e){ObjectNode n=o();if(e==null)return n;text(n,"employerName",e.getEmployer());text(n,"employmentType",e.getEmploymentType());num(n,"experienceYears",e.getExperienceYears());bool(n,"salaried",e.getSalaried());text(n,"designation",e.getDesignation());return n;}
 private ObjectNode address(Address a){ObjectNode n=o();if(a==null)return n;text(n,"houseNumber",a.getHouseNo());text(n,"street",a.getStreet());text(n,"city",a.getCity());text(n,"state",a.getState());text(n,"country",a.getCountry());text(n,"postalCode",a.getPostalCode());return n;}
 private ObjectNode credit(CreditHistory c){ObjectNode n=o();if(c==null)return n;num(n,"creditScore",c.getCreditScore());num(n,"activeLoans",c.getActiveLoans());bool(n,"loanDefault",c.getLoanDefault());num(n,"outstandingAmount",c.getOutstandingAmount());return n;}
 private ObjectNode income(Income i){ObjectNode n=o();if(i==null)return n;num(n,"monthlyIncome",i.getMonthlyIncome());num(n,"annualIncome",i.getAnnualIncome());num(n,"otherIncome",i.getOtherIncome());return n;}
 private ObjectNode bank(BankDetails b){ObjectNode n=o();if(b==null)return n;text(n,"accountNumber",b.getAccountNumber());text(n,"bankName",b.getBankName());text(n,"accountType",b.getAccountType());num(n,"balance",b.getBalance());return n;}
 private ObjectNode loan(Loan l){ObjectNode n=o();if(l==null)return n;text(n,"loanId",l.getLoanId());text(n,"loanType",l.getLoanType());n.set("details",loanDetails(l.getDetails()));n.set("collateral",collateral(l.getCollateral()));return n;}
 private ObjectNode loanDetails(LoanDetails d){ObjectNode n=o();if(d==null)return n;num(n,"loanAmount",d.getLoanAmount());num(n,"tenureMonths",d.getTenureMonths());num(n,"interestRate",d.getInterestRate());text(n,"purpose",d.getPurpose());text(n,"repaymentType",d.getRepaymentType());return n;}
 private ObjectNode collateral(Collateral c){ObjectNode n=o();if(c==null)return n;text(n,"collateralType",c.getCollateralType());num(n,"marketValue",c.getMarketValue());bool(n,"verified",c.getVerified());return n;}
 private ObjectNode o(){return mapper.createObjectNode();} private void text(ObjectNode n,String k,String v){if(v!=null)n.put(k,v);} private void num(ObjectNode n,String k,Number v){if(v!=null)n.set(k,mapper.valueToTree(v));} private void bool(ObjectNode n,String k,Boolean v){if(v!=null)n.put(k,v);} private String pretty(String b){try{JsonNode n=mapper.readTree(b);return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(n);}catch(Exception e){return b;}}
}
