package com.company.loan.controller;

import jakarta.validation.constraints.*;

public class LoanForm {
 @NotBlank private String applicantId; @NotBlank private String firstName; @NotBlank private String lastName; @NotNull @Min(18) @Max(100) private Integer age; @NotBlank private String gender;
 private String pan,aadhaar,maritalStatus; @Min(0) private Integer dependents; private Boolean existingCustomer;
 private String employer,employmentType,designation; @Min(0) private Integer experienceYears; private Boolean salaried;
 @NotNull @PositiveOrZero private Long monthlyIncome; @PositiveOrZero private Long annualIncome,otherIncome;
 private String houseNo,street,city,state,country,postalCode; @Min(300) @Max(900) private Integer creditScore; @Min(0) private Integer activeLoans; @PositiveOrZero private Long outstandingAmount; private Boolean loanDefault;
 private String bankName,accountNumber,accountType; @PositiveOrZero private Long balance;
 @NotBlank private String loanId; @NotBlank private String loanType; @NotNull @Positive private Long loanAmount; @NotNull @Min(1) @Max(480) private Integer tenureMonths; @NotNull @DecimalMin("0.0") private Double interestRate; private String purpose,repaymentType,collateralType; @PositiveOrZero private Long marketValue; private Boolean verified;
 public String getApplicantId(){return applicantId;} public void setApplicantId(String v){applicantId=v;} public String getFirstName(){return firstName;} public void setFirstName(String v){firstName=v;} public String getLastName(){return lastName;} public void setLastName(String v){lastName=v;} public Integer getAge(){return age;} public void setAge(Integer v){age=v;} public String getGender(){return gender;} public void setGender(String v){gender=v;}
 public String getPan(){return pan;} public void setPan(String v){pan=v;} public String getAadhaar(){return aadhaar;} public void setAadhaar(String v){aadhaar=v;} public String getMaritalStatus(){return maritalStatus;} public void setMaritalStatus(String v){maritalStatus=v;} public Integer getDependents(){return dependents;} public void setDependents(Integer v){dependents=v;} public Boolean getExistingCustomer(){return existingCustomer;} public void setExistingCustomer(Boolean v){existingCustomer=v;}
 public String getEmployer(){return employer;} public void setEmployer(String v){employer=v;} public String getEmploymentType(){return employmentType;} public void setEmploymentType(String v){employmentType=v;} public String getDesignation(){return designation;} public void setDesignation(String v){designation=v;} public Integer getExperienceYears(){return experienceYears;} public void setExperienceYears(Integer v){experienceYears=v;} public Boolean getSalaried(){return salaried;} public void setSalaried(Boolean v){salaried=v;}
 public Long getMonthlyIncome(){return monthlyIncome;} public void setMonthlyIncome(Long v){monthlyIncome=v;} public Long getAnnualIncome(){return annualIncome;} public void setAnnualIncome(Long v){annualIncome=v;} public Long getOtherIncome(){return otherIncome;} public void setOtherIncome(Long v){otherIncome=v;}
 public String getHouseNo(){return houseNo;} public void setHouseNo(String v){houseNo=v;} public String getStreet(){return street;} public void setStreet(String v){street=v;} public String getCity(){return city;} public void setCity(String v){city=v;} public String getState(){return state;} public void setState(String v){state=v;} public String getCountry(){return country;} public void setCountry(String v){country=v;} public String getPostalCode(){return postalCode;} public void setPostalCode(String v){postalCode=v;}
 public Integer getCreditScore(){return creditScore;} public void setCreditScore(Integer v){creditScore=v;} public Integer getActiveLoans(){return activeLoans;} public void setActiveLoans(Integer v){activeLoans=v;} public Long getOutstandingAmount(){return outstandingAmount;} public void setOutstandingAmount(Long v){outstandingAmount=v;} public Boolean getLoanDefault(){return loanDefault;} public void setLoanDefault(Boolean v){loanDefault=v;}
 public String getBankName(){return bankName;} public void setBankName(String v){bankName=v;} public String getAccountNumber(){return accountNumber;} public void setAccountNumber(String v){accountNumber=v;} public String getAccountType(){return accountType;} public void setAccountType(String v){accountType=v;} public Long getBalance(){return balance;} public void setBalance(Long v){balance=v;}
 public String getLoanId(){return loanId;} public void setLoanId(String v){loanId=v;} public String getLoanType(){return loanType;} public void setLoanType(String v){loanType=v;} public Long getLoanAmount(){return loanAmount;} public void setLoanAmount(Long v){loanAmount=v;} public Integer getTenureMonths(){return tenureMonths;} public void setTenureMonths(Integer v){tenureMonths=v;} public Double getInterestRate(){return interestRate;} public void setInterestRate(Double v){interestRate=v;} public String getPurpose(){return purpose;} public void setPurpose(String v){purpose=v;} public String getRepaymentType(){return repaymentType;} public void setRepaymentType(String v){repaymentType=v;} public String getCollateralType(){return collateralType;} public void setCollateralType(String v){collateralType=v;} public Long getMarketValue(){return marketValue;} public void setMarketValue(Long v){marketValue=v;} public Boolean getVerified(){return verified;} public void setVerified(Boolean v){verified=v;}
}
